name: 'Go Unit Test Coverage Report'
description: 'Add a comment to pull requests which summarizes code coverage results.'
author: "Friedrich Große"

inputs:
  coverage-artifact-name:
    description: 'The name of the artifact containing the code coverage results'
    required: true
    default: 'code-coverage'
  coverage-file-name:
    description: 'The name of the file containing the code coverage results'
    required: true
    default: 'coverage.txt'
  prefix:
    description: |
      A prefix to add to all paths in the JSON file of changed files.
      This is useful to map the changed files (e.g., ["foo/my_file.go"] to their
      coverage profile which uses the full package name to identify the files
      (e.g., "github.com/fgrosse/example/foo/my_file.go"). Note that currently,
      packages with a different name than their directory are not supported.
    required: false
    default: ${{ github.repository }}
  trim:
    description: Trim a prefix in the "Impacted Packages" column of the markdown report
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.22

    - name: Install go-coverage-report
      shell: bash
      run: go install github.com/fgrosse/go-coverage-report@5f897d332e09b79317ab9ae7754d20497fa62e0d

    - name: Determine changed files
      id: changed-files
      uses: tj-actions/changed-files@aa08304bd477b800d468db44fe10f6c61f7f7b11 # v42.1.0
      with:
        write_output_files: true
        json: true
        files: |
          **.go
        files_ignore: |
          **_test.go
          vendor/**

    - name: Code coverage report
      shell: bash
      run: $GITHUB_ACTION_PATH/github-action.sh ${{ github.repository }} ${{ github.event.pull_request.number }} ${{ github.run_id }}
      env:
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_BASE_REF: ${{ github.base_ref }}
        CHANGED_FILES_PATH: .github/outputs/all_changed_files.json
        COVERAGE_ARTIFACT_NAME: ${{ inputs.coverage-artifact-name }}
        COVERAGE_FILE_NAME: ${{ inputs.coverage-file-name }}
        COVERAGE_REPORT_PREFIX: ${{ inputs.prefix }}
        COVERAGE_REPORT_TRIM: ${{ inputs.trim }}
